### ISSUE TITLE
[BUG] Various imprecisions prevent compilation with -Wall -Werror

### ISSUE THREAD

**Issue by dario-loi** [lvntky/fbgl#3]
By enforcing static type checks, the header library fails compilation due to a variety of common errors:

- [x] An inconsistent type convention used to represent framebuffer dimensions, sometimes `int` is used, sometimes `size_t` is used. For example in `fbgl_draw_rectangle_outline` `int x` is compared with the result of `fbgl_point_t::x`, which is of type `size_t` (signed and unsigned comparison)
- [x] `abs` is called on `size_t` variables in the fbgl_draw_line function, if one wishes the `x` and `y` points to be used interchangeably, they should be signed types so that the `abs` trick can work without overflows
- [x] Past line 430 (`#endif // FBGL_USE_FREETYPE`), the rest of the implementation is outside of the `FBGL_IMPLEMENTATION` include guard, this may lead to ODR violation.

**Comment by lvntky** [comment]
These are quite important actually, thank you for reporting. You can assign the issues if you want to fix them! Otherwise i will take a look, i know couple of places are quite sloopy implemented. 😄

**Comment by dario-loi** [comment]
@lvntky I'll use this issue to continue the discussion under #6, it's weird, I used clang-format and it seems to have removed some but not all of the formatting, hope the result is not too messy.

If you want to open a dev/staging branch, I'll open another PR to that so we can triage eventual bad formatting errors

**Comment by lvntky** [comment]
> @lvntky I'll use this issue to continue the discussion under #6, it's weird, I used clang-format and it seems to have removed some but not all of the formatting, hope the result is not too messy.
> 
> If you want to open a dev/staging branch, I'll open another PR to that so we can triage eventual bad formatting errors

I think it's all good now, should we close the other 2 issues ?

**Comment by dario-loi** [comment]
Yeah we got everything with #8, we can close them.
