### ISSUE TITLE
[BUG] WIN32 API structs used

### ISSUE THREAD

**Issue by dario-loi** [lvntky/fbgl#4]
This might be a me problem and not a problem of the library, but, when compiling, I currently get errors such as:

```
fbgl.h: In function ‘fbgl_check_esc_key’:
fbgl.h:343:12: error: variable ‘tv’ has initializer but incomplete type
  343 |     struct timeval tv = { 0, 0 }; // Timeout of 0, to poll immediately
```

When googling, it seems that this `timeval` struct is defined as part of the windows API? (https://learn.microsoft.com/it-it/windows/win32/api/winsock2/ns-winsock2-timeval), is this true or is there another UNIX struct of the same name that is being implicitly linked?

**Comment by lvntky** [comment]
it's actually coming from [sys/time.h](https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_418.html) and maybe there is a Windows equivelent of it but i dont know anything about it. Anyways the check esc key is already quite buggy in current state especially in raw mode. I wil take a look maybe this two issues are linked.

**Comment by lvntky** [comment]
> Ok thank you for the extra info, it seems then that it's just a problem of the header not being imported. I prepared a commit with a bunch of bug fixes to all the issues I raised, I'll wait for the current PR to be handled so that I can open another and we can integrate all this stuff into main.

Thats fantastic,  i just commented out the pr
